jobs:
  my-job:
    runs-on: windows-latest
    env:
      MY_SECRET: ${{ secrets.CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add more steps as needed
